[general]
import = [
    "~/.config/alacritty/themes/themes/zenburn.toml"
]

[font]
size = 18.0

[font.normal]
family = "MesloLGS Nerd Font"

[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Control"

[window]
decorations = "none"
